version: "3.8"
services:
# ####################################################################################   Launch emulator device and starting appium instance
  Android-Service:
    image: amrka/ultimate-android:latest
    build: .
    ports:
      - 4725:4725                                                              ## Android/Appium Service
    container_name: Android-Service
    environment:
      APPIUM_PORT: 4725
    privileged: true
    command:
       bash -c './start_emu_headless.sh && ./start_appium.sh'
    tty: true
    stdin_open: true
###################################################################################   Clone you github repository and run script (JAVA/JS)
  Clone-Service:
    image: amrka/ultimate-android:latest
    build: .
    ports:
      - 4700:4700
    container_name: Clone-Service
    environment:
      BRANCH: main                                                             ##Github Repo branch
      GITHUB_USERNAME: amrkamel1                                               ##Github Username
      GITHUB_TOKEN: ghp_wZIj4X7WtvB6xBmdvp                                     ##Github Personal token
      REPO_NAME:  automation                                                   ##Github repo exact name
      TEST_SCRIPT: 'mvn test'                                                  ## e.g "npm run test" ,Note you dont need to run npm install
      REPORT: allure                                                           
      REPORT_DIR: './'
    privileged: true
    command:
       bash -c './clone_repo.sh && ./execute_test.sh'                          ## Shell scripts for clonning and executing the test script
    tty: true
    stdin_open: true
# ####################################################################################   Start selenium instance
  Selenium-Service:
    image: amrka/ultimate-android:latest
    build: .
    ports:
      - 4444:4444                                                              ##FOR SELENIUM SERVER  
    container_name: Selenium-Service
    environment: 
      BROWSER: 'firefox'                                                       ## If empty chrome browser will be the default value, otherwise use firefox 
    command:
      bash -c './start_selenium.sh'                                            ## Starting selenium server
    tty: true
    stdin_open: true
# ####################################################################################   Start VNC sever so you can have remote access to the docker machine in VNC ui
  VNC-Service:
    image: amrka/ultimate-android:latest
    build: .
    ports:
      - 5900:5900                                                               ## VNC Service
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: Test123!!
    privileged: true
    command:
      bash -c './bootstrap.sh'                                                  ## Starting VNC Service
    tty: true
    stdin_open: true
